package com.example.fancup;

import java.util.List;

public class Jogadores {

    public static class Jogador {
        private final String nome;
        private final String clube;
        private final String posicao;
        public Jogador(String nome, String clube, String posicao) {
            this.nome = nome;
            this.clube = clube;
            this.posicao = posicao;
        }
        public String getNome() {
            return nome;
        }
        public String getClube() {
            return clube;
        }
        public String getPosicao() {
            return posicao;
        }
        @Override
        public String toString() {
            return nome + " (" + clube + ") - " + posicao;
        }
    }

    public static class Selecao {
        private final String nome;
        private final List<Jogador> jogadores;
        public Selecao(String nome, List<Jogador> jogadores) {
            this.nome = nome;
            this.jogadores = jogadores;
        }
        public String getNome() {
            return nome;
        }
        public List<Jogador> getJogadores() {
            return jogadores;
        }
        @Override
        public String toString() {
            return "Seleção " + nome + " " + jogadores;
        }
    }

    public static final List<Selecao> SELECOES = List.of(
        new Selecao("México", List.of(
            new Jogador("Raúl Rangel","Chivas Guadalajara","Goleiro"),
            new Jogador("Carlos Acevedo","Santos Laguna","Goleiro"),
            new Jogador("Guillermo Ochoa","AEL Limassol","Goleiro"),
            new Jogador("Jorge Sánchez","PAOK","Defensor"),
            new Jogador("César Montes","Lokomotiv Moscou","Defensor"),
            new Jogador("Edson Álvarez","Fenerbahçe","Defensor"),
            new Jogador("Joah Vásquez","Genoa","Defensor"),
            new Jogador("Erik Lira","Cruz Azul","Defensor"),
            new Jogador("Luis Romo","Chivas Guadalajara","Defensor"),
            new Jogador("Israel Reyes","América-MEX","Defensor"),
            new Jogador("Mateo Chávez","AZ","Defensor"),
            new Jogador("Jesús Gallardo","Toluca","Defensor"),
            new Jogador("Álvaro Fidalgo","Real Betis","Meio-campista"),
            new Jogador("Orbelín Pineda","AEK","Meio-campista"),
            new Jogador("Obed Vargas","Atlético de Madrid","Meio-campista"),
            new Jogador("Gilberto Mora","Tijuana","Meio-campista"),
            new Jogador("César Huerta","Anderlecht","Meio-campista"),
            new Jogador("Luis Chávez","Dínamo de Moscou","Meio-campista"),
            new Jogador("Roberto Alvarado","Chivas Guadalajara","Meio-campista"),
            new Jogador("Brian Gutiérrez","Chivas Guadalajara","Meio-campista"),
            new Jogador("Raúl Jiménez","Fulham","Atacante"),
            new Jogador("Alexis Veja","Toluca","Atacante"),
            new Jogador("Santiago Giménez","Milan","Atacante"),
            new Jogador("Armando González","Chivas Guadalajara","Atacante"),
            new Jogador("Julián Quiñones","Al Qadsiah","Atacante"),
            new Jogador("Guillermo Martínez","Pumas","Atacante")
        )),
        new Selecao("África do Sul", List.of(
            new Jogador("Ronwen Williams","Mamelodi Sundowns","Goleiro"),
            new Jogador("Ricardo Goss","Siwelele FC","Goleiro"),
            new Jogador("Sipho Chaine","Orlando Pirates","Goleiro"),
            new Jogador("Khuliso Mudau","Mamelodi Sundowns","Defensor"),
            new Jogador("Nkosinathi Sibisi","Orlando Pirates","Defensor"),
            new Jogador("Ime Okon","Hannover 96","Defensor"),
            new Jogador("Khulumani Ndamane","Mamelodi Sundowns","Defensor"),
            new Jogador("Aubrey Modiba","Mamelodi Sundowns","Defensor"),
            new Jogador("Samukele Kabini","Molde FK","Defensor"),
            new Jogador("Thabang Matuludi","Polokwane City","Defensor"),
            new Jogador("Olwethu Makhanya","Philadelphia Union","Defensor"),
            new Jogador("Kamogelo Sebelebele","Orlando Pirates","Defensor"),
            new Jogador("Bradley Cross","Kaizer Chiefs","Defensor"),
            new Jogador("Mbekezeli Mbokazi","Chicago Fire","Defensor"),
            new Jogador("Teboho Mokoena","Mamelodi Sundowns","Meio-campista"),
            new Jogador("Thalente Mbatha","Orlando Pirates","Meio-campista"),
            new Jogador("Sphephelo Sithole","Tondela","Meio-campista"),
            new Jogador("Jayden Adams","Mamelodi Sundowns","Meio-campista"),
            new Jogador("Oswin Appollis","Orlando Pirates","Atacante"),
            new Jogador("Iqraam Rayners","Mamelodi Sundowns","Atacante"),
            new Jogador("Tshepang Moremi","Orlando Pirates","Atacante"),
            new Jogador("Relebohile Mofokeng","Orlando Pirates","Atacante"),
            new Jogador("Evidence Makgopa","Orlando Pirates","Atacante"),
            new Jogador("Themba Zwane","Mamelodi Sundowns","Atacante"),
            new Jogador("Lyle Foster","Burnley","Atacante"),
            new Jogador("Thapelo Maseko","AEL Limassol","Atacante")
        )),
        new Selecao("Coreia do Sul", List.of(
            new Jogador("Kim Seunggyu","FC Tokyo","Goleiro"),
            new Jogador("Song Bumkeun","Jeonbuk Hyundai","Goleiro"),
            new Jogador("Jo Hyeonwoo","Ulsan HD","Goleiro"),
            new Jogador("Kim Moonhwan","Daejon Hana Citizen","Defensor"),
            new Jogador("Kim Min-jae","Bayern de Munique","Defensor"),
            new Jogador("Kim Taehyeon","Kashima Antlers","Defensor"),
            new Jogador("Park Jinseob","Jeonbuk FC","Defensor"),
            new Jogador("Seol Youngwoo","Crvena Zvezda","Defensor"),
            new Jogador("Jens Castrop","Borussia Mönchengladbach","Defensor"),
            new Jogador("Lee Kihyuk","Gangwon FC","Defensor"),
            new Jogador("Lee Taeseok","Austria Wien","Defensor"),
            new Jogador("Lee Hanbeom","Midtjylland","Defensor"),
            new Jogador("Cho Yumin","Sharjah FC","Defensor"),
            new Jogador("Kim Jingyu","Jeonbuk Hyundai","Meio-campista"),
            new Jogador("Bae Junho","Stoke City","Meio-campista"),
            new Jogador("Paik Seungho","Birmingham City","Meio-campista"),
            new Jogador("Yang Hyunjun","Celtic","Meio-campista"),
            new Jogador("Eom Jisung","Swansea City","Meio-campista"),
            new Jogador("Lee Kang-in","Paris Saint-Germain","Meio-campista"),
            new Jogador("Lee Donggyeong","Ulsan HD","Meio-campista"),
            new Jogador("Lee Jaesung","Mainz","Meio-campista"),
            new Jogador("Hwang Inbeom","Feyenoord","Meio-campista"),
            new Jogador("Hwang Heechan","Wolverhampton","Meio-campista"),
            new Jogador("Son Heung-min","LA FC","Atacante"),
            new Jogador("Oh Hyeongyu","Genk","Atacante"),
            new Jogador("Cho Gue-sung","Midtjylland","Atacante")
        )),
        new Selecao("República Tcheca", List.of(
            new Jogador("Lukás Hornícek","Braga","Goleiro"),
            new Jogador("Matej Kovár","PSV","Goleiro"),
            new Jogador("Jindrich Stanek","Slavia Praga","Goleiro"),
            new Jogador("Vladimír Coufal","Hoffenheim","Defensor"),
            new Jogador("David Doudera","Slavia Praga","Defensor"),
            new Jogador("Tomás Holes","Slavia Praga","Defensor"),
            new Jogador("Robin Hranác","Hoffenheim","Defensor"),
            new Jogador("Stepán Chaloupek","Slavia Praga","Defensor"),
            new Jogador("David Jurásek","Slavia Praga","Defensor"),
            new Jogador("Ladislav Krejcí","Wolverhampton","Defensor"),
            new Jogador("Jaroslav Zeleny","Sparta Praga","Defensor"),
            new Jogador("David Zima","Slavia Praga","Defensor"),
            new Jogador("Lukás Cerv","Viktoria Plzen","Meio-campista"),
            new Jogador("Vladimír Darida","Hradec Králové","Meio-campista"),
            new Jogador("Lukás Provod","Slavia Praga","Meio-campista"),
            new Jogador("Michal Sadílek","Slavia Praga","Meio-campista"),
            new Jogador("Hugo Sochurek","Sparta Praga","Meio-campista"),
            new Jogador("Alexandr Sojka","Viktoria Plzen","Meio-campista"),
            new Jogador("Tomás Soucek","West Ham","Meio-campista"),
            new Jogador("Pavel Sulc","Lyon","Meio-campista"),
            new Jogador("Denis Visinsky","Viktoria Plzen","Meio-campista"),
            new Jogador("Adam Hlozek","Hoffenheim","Atacante"),
            new Jogador("Tomás Chory","Slavia Praga","Atacante"),
            new Jogador("Mojmír Chytil","Slavia Praga","Atacante"),
            new Jogador("Patrik Schick","Bayer Leverkusen","Atacante"),
            new Jogador("Jan Kuchta","Sparta Praga","Atacante")
        )),
        new Selecao("Canadá", List.of(
            new Jogador("Dayne St. Clair","Inter Miami","Goleiro"),
            new Jogador("Maxim Crépeau","Orlando City","Goleiro"),
            new Jogador("Owen Goodman","Crystal Palace","Goleiro"),
            new Jogador("Alistair Johnston","Celtic","Defensor"),
            new Jogador("Derek Cornelius","Olympique de Marselha","Defensor"),
            new Jogador("Richie Laryea","Toronto FC","Defensor"),
            new Jogador("Kiko Sigur","Hajduk Split","Defensor"),
            new Jogador("Joel Waterman","Chicago Fire","Defensor"),
            new Jogador("Luc de Fougerolles","Fulham","Defensor"),
            new Jogador("Moise Bombito","Nice","Defensor"),
            new Jogador("Alfie Jones","Middlesbrough","Defensor"),
            new Jogador("Alphonso Davies","Bayern de Munique","Defensor"),
            new Jogador("Stephen Eustáquio","Porto","Meio-campista"),
            new Jogador("Ismael Koné","Sassuolo","Meio-campista"),
            new Jogador("Tajon Buchanan","Villarreal","Meio-campista"),
            new Jogador("Mathieu Choinière","Los Angeles FC","Meio-campista"),
            new Jogador("Ali Ahmed","Norwich City","Meio-campista"),
            new Jogador("Nathan Saliba","Anderlecht","Meio-campista"),
            new Jogador("Liam Millar","Hull City","Meio-campista"),
            new Jogador("Marcelo Flores","Tigres","Meio-campista"),
            new Jogador("Jacob Shaffelburg","Los Angeles FC","Meio-campista"),
            new Jogador("Jonathan Osorio","Toronto FC","Meio-campista"),
            new Jogador("Jonathan David","Juventus","Atacante"),
            new Jogador("Cyle Larin","Southampton","Atacante"),
            new Jogador("Tani Oluwaseyi","Villarreal","Atacante"),
            new Jogador("Promise David","Union Saint-Gilloise","Atacante")
        )),
        new Selecao("Bósnia e Herzegovina", List.of(
            new Jogador("Nikola Vasilj","St. Pauli","Goleiro"),
            new Jogador("Martin Zlomislić","HNK Rijeka","Goleiro"),
            new Jogador("Osman Hadžikić","Slaven Belupo Koprivnica","Goleiro"),
            new Jogador("Sead Kolašinac","Atalanta","Defensor"),
            new Jogador("Amar Dedić","Benfica","Defensor"),
            new Jogador("Nihad Mujakić","Gaziantep","Defensor"),
            new Jogador("Nikola Katić","Schalke 04","Defensor"),
            new Jogador("Tarik Muharemović","Sassuolo","Defensor"),
            new Jogador("Stjepan Radeljić","HNK Rijeka","Defensor"),
            new Jogador("Dennis Hadžikadunić","Sampdoria","Defensor"),
            new Jogador("Nidal Čelik","Lens","Defensor"),
            new Jogador("Amir Hadžiahmetović","Hull City","Meio-campista"),
            new Jogador("Ivan Šunjić","Pafos","Meio-campista"),
            new Jogador("Ivan Bašić","Astana","Meio-campista"),
            new Jogador("Dzenis Burnić","Karlsruher","Meio-campista"),
            new Jogador("Ermin Mahmić","Slovan Liberec","Meio-campista"),
            new Jogador("Benjamin Tahirović","Brøndby","Meio-campista"),
            new Jogador("Amar Memić","Viktoria Plzen","Meio-campista"),
            new Jogador("Armin Gigović","Young Boys","Meio-campista"),
            new Jogador("Kerim Alajbegović","Red Bull Salzburg","Meio-campista"),
            new Jogador("Esmir Bajraktarević","PSV","Meio-campista"),
            new Jogador("Ermedin Demirović","Stuttgart","Atacante"),
            new Jogador("Jovo Lukić","Universitatea Cluj","Atacante"),
            new Jogador("Samed Baždar","Jagiellonia Białystok","Atacante"),
            new Jogador("Haris Tabaković","Borussia Mönchengladbach","Atacante"),
            new Jogador("Edin Džeko","Schalke 04","Atacante")
        )),
        new Selecao("Catar", List.of(
            new Jogador("Mahmoud Abunada","Al Rayyan","Goleiro"),
            new Jogador("Meshaal Barsham","Al Sadd","Goleiro"),
            new Jogador("Salah Zakaria","Al Duhail","Goleiro"),
            new Jogador("Ayoub Al Alawi","Al Gharafa","Defensor"),
            new Jogador("Boualem Khoukhi","Al Sadd","Defensor"),
            new Jogador("Homam Al Amin","Al Duhail","Defensor"),
            new Jogador("Lucas Mendes","Al Wakrah","Defensor"),
            new Jogador("Issa Laye","Al Arabi","Defensor"),
            new Jogador("Pedro Miguel","Al Sadd","Defensor"),
            new Jogador("Al Hashmi Al Hussain","Al Arabi","Defensor"),
            new Jogador("Sultan Al Brake","Al Duhail","Defensor"),
            new Jogador("Assim Madibo","Al Duhail","Meio-campista"),
            new Jogador("Abdulaziz Hatem","Al Rayyan","Meio-campista"),
            new Jogador("Ahmed Fathy","Pyramids","Meio-campista"),
            new Jogador("Karim Boudiaf","Al Duhail","Meio-campista"),
            new Jogador("Jassem Gaber","Al Rayyan","Meio-campista"),
            new Jogador("Mohamed Mannaj","Al Shamal","Meio-campista"),
            new Jogador("Ahmed Al Ganehi","Al Gharafa","Atacante"),
            new Jogador("Ahmed Alaa","Al Rayyan","Atacante"),
            new Jogador("Akram Afif","Al Sadd","Atacante"),
            new Jogador("Almoez Ali","Al Duhail","Atacante"),
            new Jogador("Edmilson Junior","Al Duhail","Atacante"),
            new Jogador("Hasan Al Haydos","Al Sadd","Atacante"),
            new Jogador("Mohammed Muntari","Al Gharafa","Atacante"),
            new Jogador("Tahsin Mohammed","Al Duhail","Atacante"),
            new Jogador("Youssef Abdulrazzaq","Al Sadd","Atacante")
        )),
        new Selecao("Suíça", List.of(
            new Jogador("Marvin Keller","Young Boys","Goleiro"),
            new Jogador("Gregor Kobel","Borussia Dortmund","Goleiro"),
            new Jogador("Yvon Mvogo","Lorient","Goleiro"),
            new Jogador("Manuel Akanji","Inter de Milão","Defensor"),
            new Jogador("Aurèle Amenda","Eintracht Frankfurt","Defensor"),
            new Jogador("Eray Comert","Valencia","Defensor"),
            new Jogador("Nico Elvedi","Borussia Mönchengladbach","Defensor"),
            new Jogador("Luca Jaquez","Stuttgart","Defensor"),
            new Jogador("Miro Muheim","Hamburgo","Defensor"),
            new Jogador("Ricardo Rodriguez","Real Betis","Defensor"),
            new Jogador("Silvan Widmer","Mainz","Defensor"),
            new Jogador("Michel Aebischer","Pisa","Meio-campista"),
            new Jogador("Christian Fassnacht","Young Boys","Meio-campista"),
            new Jogador("Remo Freuler","Bologna","Meio-campista"),
            new Jogador("Ardon Jashari","Milan","Meio-campista"),
            new Jogador("Johan Manzambi","Freiburg","Meio-campista"),
            new Jogador("Fabian Rieder","Augsburg","Meio-campista"),
            new Jogador("Djibril Sow","Sevilla","Meio-campista"),
            new Jogador("Granit Xhaka","Sunderland","Meio-campista"),
            new Jogador("Denis Zakaria","Monaco","Meio-campista"),
            new Jogador("Zeki Amdouni","Burnley","Atacante"),
            new Jogador("Breel Embolo","Stade Rennais","Atacante"),
            new Jogador("Cedric Itten","Fortuna Dusseldorf","Atacante"),
            new Jogador("Ruben Vargas","Sevilla","Atacante"),
            new Jogador("Dan Ndoye","Nottingham Forest","Atacante"),
            new Jogador("Noah Okafor","Leeds United","Atacante")
        )),
        new Selecao("Brasil", List.of(
            new Jogador("Alisson","Liverpool","Goleiro"),
            new Jogador("Ederson","Fenerbahçe","Goleiro"),
            new Jogador("Weverton","Grêmio","Goleiro"),
            new Jogador("Marquinhos","Paris Saint-Germain","Defensor"),
            new Jogador("Gabriel Magalhães","Arsenal","Defensor"),
            new Jogador("Bremer","Juventus","Defensor"),
            new Jogador("Danilo","Flamengo","Defensor"),
            new Jogador("Ibañez","Al Ahli","Defensor"),
            new Jogador("Alex Sandro","Flamengo","Defensor"),
            new Jogador("Douglas Santos","Zenit","Defensor"),
            new Jogador("Wesley","Roma","Defensor"),
            new Jogador("Bruno Guimarães","Newcastle","Meio-campista"),
            new Jogador("Casemiro","Manchester United","Meio-campista"),
            new Jogador("Danilo","Botafogo","Meio-campista"),
            new Jogador("Lucas Paquetá","Flamengo","Meio-campista"),
            new Jogador("Fabinho","Al Ittihad","Meio-campista"),
            new Jogador("Neymar","Santos","Atacante"),
            new Jogador("Raphinha","Barcelona","Atacante"),
            new Jogador("Vinícius Júnior","Real Madrid","Atacante"),
            new Jogador("Matheus Cunha","Manchester United","Atacante"),
            new Jogador("Rayan","Bournemouth","Atacante"),
            new Jogador("Gabriel Martinelli","Arsenal","Atacante"),
            new Jogador("Luiz Henrique","Zenit","Atacante"),
            new Jogador("Endrick","Lyon","Atacante"),
            new Jogador("Igor Thiago","Brentford","Atacante")
        )),
        new Selecao("Marrocos", List.of(
            new Jogador("Yassine Bounou","Al Hilal","Goleiro"),
            new Jogador("Munir El Kajoui","Berkane","Goleiro"),
            new Jogador("Ahmed Reda Tagnaouti","AS FAR","Goleiro"),
            new Jogador("Achraf Hakimi","Paris Saint-Germain","Defensor"),
            new Jogador("Noussair Mazraoui","Manchester United","Defensor"),
            new Jogador("Anass Salah-Eddine","PSV","Defensor"),
            new Jogador("Youssef Belammari","Al Ahly","Defensor"),
            new Jogador("Nayef Aguerd","Olympique de Marselha","Defensor"),
            new Jogador("Issa Diop","Fulham","Defensor"),
            new Jogador("Chadi Riad","Crystal Palace","Defensor"),
            new Jogador("Redouane Halhal","KV Mechelen","Defensor"),
            new Jogador("Zakaria El Ouahdi","Genk","Defensor"),
            new Jogador("Azzedine Ounahi","Girona","Meio-campista"),
            new Jogador("Neil El Aynaoui","Roma","Meio-campista"),
            new Jogador("Sofyan Amrabat","Real Betis","Meio-campista"),
            new Jogador("Ayoub Bouaddi","Lille","Meio-campista"),
            new Jogador("Samir El Mourabet","Strasbourg","Meio-campista"),
            new Jogador("Bilal El Khannouss","Stuttgart","Meio-campista"),
            new Jogador("Ismaël Saibari","PSV","Meio-campista"),
            new Jogador("Brahim Díaz","Real Madrid","Atacante"),
            new Jogador("Abdessamad Ezzalzouli","Real Betis","Atacante"),
            new Jogador("Yassine Bessime","Strasbourg","Atacante"),
            new Jogador("Chemsdine Talbi","Sunderland","Atacante"),
            new Jogador("Soufiane Rahimi","Al Ain","Atacante"),
            new Jogador("Ayoub El Kaabi","Olympiacos","Atacante"),
            new Jogador("Ayoubе Amahount","Eintracht Frankfurt","Atacante")
        )),
        new Selecao("Haiti", List.of(
            new Jogador("Johnny Placide","Bastia","Goleiro"),
            new Jogador("Alexandre Pierre","Sochaux","Goleiro"),
            new Jogador("Josué Duverger","Cosmos Koblenz","Goleiro"),
            new Jogador("Carlens Arcus","Angers","Defensor"),
            new Jogador("Wilguens Pauguain","SV Zulte Waregem","Defensor"),
            new Jogador("Duke Lacroix","Colorado Springs","Defensor"),
            new Jogador("Martin Experience","Nancy-Lorraine","Defensor"),
            new Jogador("JK Duverne","Gent","Defensor"),
            new Jogador("Ricardo Ade","LDU","Defensor"),
            new Jogador("Hannes Delcroix","Lugano","Defensor"),
            new Jogador("Keeto Thermoncy","Young Boys II","Defensor"),
            new Jogador("Leverton Pierre","Vizela","Meio-campista"),
            new Jogador("Carl-Fred Sainthe","El Paso Locomotive","Meio-campista"),
            new Jogador("Jean-Jacques Danley","Philadelphia Union","Meio-campista"),
            new Jogador("Jeanricner Bellegarde","Wolverhampton","Meio-campista"),
            new Jogador("Pierre Woodenski","Violette","Meio-campista"),
            new Jogador("Dominique Simon","Tatran Presov","Meio-campista"),
            new Jogador("Louicius Deedson","Dallas","Atacante"),
            new Jogador("Ruben Providence","Almere City","Atacante"),
            new Jogador("Josué Casimir","Auxerre","Atacante"),
            new Jogador("Derrick Etienne","Toronto FC","Atacante"),
            new Jogador("Wilson Isidor","Sunderland","Atacante"),
            new Jogador("Duckens Nazon","Esteghlal","Atacante"),
            new Jogador("Frantzdy Pierrot","Çaykur Rizespor","Atacante"),
            new Jogador("Yassin Fortune","Vizela","Atacante"),
            new Jogador("Lenny Joseph","Ferencváros","Atacante")
        )),
        new Selecao("Escócia", List.of(
            new Jogador("Craig Gordon","Celtic","Goleiro"),
            new Jogador("Angus Gunn","Nottingham Forest","Goleiro"),
            new Jogador("Liam Kelly","Queens Park Rangers","Goleiro"),
            new Jogador("Grant Hanley","Hibernian","Defensor"),
            new Jogador("Jack Hendry","Al Ettifaq","Defensor"),
            new Jogador("Aaron Hickey","Brentford","Defensor"),
            new Jogador("Dominic Hyam","Wrexham","Defensor"),
            new Jogador("Scott McKenna","Dinamo Zagreb","Defensor"),
            new Jogador("Nathan Patterson","Everton","Defensor"),
            new Jogador("Anthony Ralston","Celtic","Defensor"),
            new Jogador("Andrew Robertson","Liverpool","Defensor"),
            new Jogador("John Souttar","Rangers","Defensor"),
            new Jogador("Kieran Tierney","Celtic","Defensor"),
            new Jogador("Ryan Christie","Bournemouth","Meio-campista"),
            new Jogador("Findlay Curtis","Rangers","Meio-campista"),
            new Jogador("Lewis Ferguson","Bologna","Meio-campista"),
            new Jogador("Ben Gannon-Doak","Bournemouth","Meio-campista"),
            new Jogador("Tyler Fletcher","Manchester United","Meio-campista"),
            new Jogador("John McGinn","Aston Villa","Meio-campista"),
            new Jogador("Kenny McLean","Norwich City","Meio-campista"),
            new Jogador("Scott McTominay","Napoli","Meio-campista"),
            new Jogador("Che Adams","Torino","Atacante"),
            new Jogador("Lyndon Dykes","Charlton Athletic","Atacante"),
            new Jogador("George Hirst","Ipswich Town","Atacante"),
            new Jogador("Lawrence Shankland","Hearts","Atacante"),
            new Jogador("Ross Steward","Southampton","Atacante")
        )),
        new Selecao("Estados Unidos", List.of(
            new Jogador("Chris Brady","Chicago Fire","Goleiro"),
            new Jogador("Matt Freese","New York City","Goleiro"),
            new Jogador("Matt Turner","New England Revolution","Goleiro"),
            new Jogador("Alex Freeman","Villarreal","Defensor"),
            new Jogador("Antonee Robinson","Fulham","Defensor"),
            new Jogador("Auston Trusty","Celtic","Defensor"),
            new Jogador("Chris Richards","Crystal Palace","Defensor"),
            new Jogador("Mark McKenzie","Toulouse","Defensor"),
            new Jogador("Max Arfsten","Columbus Crew","Defensor"),
            new Jogador("Sergiño Dest","PSV","Defensor"),
            new Jogador("Tim Ream","Charlotte","Defensor"),
            new Jogador("Miles Robinson","Cincinnati","Defensor"),
            new Jogador("Joe Scally","Borussia Mönchengladbach","Defensor"),
            new Jogador("Brenden Aaronson","Leeds United","Meio-campista"),
            new Jogador("Cristian Roldan","Seattle Sounders","Meio-campista"),
            new Jogador("Giovanni Reyna","Borussia Mönchengladbach","Meio-campista"),
            new Jogador("Malik Tillman","Bayer Leverkusen","Meio-campista"),
            new Jogador("Sebastian Berhalter","Vancouver Whitecaps","Meio-campista"),
            new Jogador("Tyler Adams","Bournemouth","Meio-campista"),
            new Jogador("Weston McKennie","Juventus","Meio-campista"),
            new Jogador("Alex Zendejas","América-MEX","Atacante"),
            new Jogador("Christian Pulisic","Milan","Atacante"),
            new Jogador("Folarin Balogun","Monaco","Atacante"),
            new Jogador("Haji Wright","Coventry City","Atacante"),
            new Jogador("Ricardo Pepi","PSV","Atacante"),
            new Jogador("Tim Weah","Olympique de Marselha","Atacante")
        )),
        new Selecao("Paraguai", List.of(
            new Jogador("Orlando Gill","San Lorenzo","Goleiro"),
            new Jogador("Gatito Fernández","Cerro Porteño","Goleiro"),
            new Jogador("Gastón Olveira","Olimpia","Goleiro"),
            new Jogador("Juan Cáceres","Dínamo de Moscou","Defensor"),
            new Jogador("José Canale","Lanús","Defensor"),
            new Jogador("Fabián Balbuena","Grêmio","Defensor"),
            new Jogador("Omar Alderete","Sunderland","Defensor"),
            new Jogador("Gustavo Gómez","Palmeiras","Defensor"),
            new Jogador("Alexandro Maidana","Talleres","Defensor"),
            new Jogador("Junior Alonso","Atlético-MG","Defensor"),
            new Jogador("Gustavo Velázquez","Cerro Porteño","Defensor"),
            new Jogador("Braian Ojeda","Orlando City","Meio-campista"),
            new Jogador("Damián Bobadilla","São Paulo","Meio-campista"),
            new Jogador("Andrés Cubas","Vancouver Whitecaps","Meio-campista"),
            new Jogador("Diego Gómez","Brighton","Meio-campista"),
            new Jogador("Kaku","Al Ain","Meio-campista"),
            new Jogador("Mauricio","Palmeiras","Meio-campista"),
            new Jogador("Matías Galarza","Atlanta United","Meio-campista"),
            new Jogador("Gustavo Caballero","Portsmouth","Atacante"),
            new Jogador("Ramón Sosa","Palmeiras","Atacante"),
            new Jogador("Miguel Almirón","Atlanta United","Atacante"),
            new Jogador("Gabriel Ávalos","Independiente","Atacante"),
            new Jogador("Isidro Pitta","Red Bull Bragantino","Atacante"),
            new Jogador("Álex Arce","Independiente RIvadavia","Atacante"),
            new Jogador("Julio Enciso","Strasbourg","Atacante"),
            new Jogador("Antonio Sanabria","Cremonese","Atacante")
        )),
        new Selecao("Austrália", List.of(
            new Jogador("Paul Izzo","Randers","Atacante"),
            new Jogador("Mathew Ryan","Levante","Atacante"),
            new Jogador("Aziz Behich","Melbourne City","Defensor"),
            new Jogador("Jordan Bos","Feyenoord","Defensor"),
            new Jogador("Cameron Burgess","Swansea City","Defensor"),
            new Jogador("Alessandro Circati","Parma","Defensor"),
            new Jogador("Milos Degenek","APOEL","Defensor"),
            new Jogador("Jason Geria","Albirex Niigata","Defensor"),
            new Jogador("Lucas Herrington","Colorado Rapids","Defensor"),
            new Jogador("Jacob Italiano","Grazer AK","Defensor"),
            new Jogador("Harry Souttar","Leicester City","Defensor"),
            new Jogador("Kai Trewin","New York City","Defensor"),
            new Jogador("Cameron Devlin","Hearts","Meio-campista"),
            new Jogador("Ajdin Hrustic","Heracles Almelo","Meio-campista"),
            new Jogador("Jackson Irvine","St. Pauli","Meio-campista"),
            new Jogador("Connor Metcalfe","St. Pauli","Meio-campista"),
            new Jogador("Paul Okon-Engstler","Sydney FC","Meio-campista"),
            new Jogador("Aiden O'Neill","New York City","Meio-campista"),
            new Jogador("Nestory Irankunda","Watford","Atacante"),
            new Jogador("Mathew Leckie","Melbourne City","Atacante"),
            new Jogador("Awer Mabil","Castellón","Atacante"),
            new Jogador("Mohamed Toure","Norwich City","Atacante"),
            new Jogador("Nishan Velupillay","Melbourne Victory","Atacante"),
            new Jogador("Cristian Volpato","Sassuolo","Atacante"),
            new Jogador("Tete Yengi","Machida Zelvia","Atacante")
        )),
        new Selecao("Turquia", List.of(
            new Jogador("Altay Bayindir","Manchester United","Goleiro"),
            new Jogador("Mert Günok","Fenerbahçe","Goleiro"),
            new Jogador("Ugurcan Çakir","Galatasaray","Goleiro"),
            new Jogador("Abdulkerim Bardakci","Galatasaray","Defensor"),
            new Jogador("Çağlar Söyüncü","Fenerbahçe","Defensor"),
            new Jogador("Eren Elmalı","Galatasaray","Defensor"),
            new Jogador("Ferdi Kadıoğlu","Brighton","Defensor"),
            new Jogador("Merih Demiral","Al Ahli","Defensor"),
            new Jogador("Mert Müldür","Fenerbahçe","Defensor"),
            new Jogador("Ozan Kabak","Hoffenheim","Defensor"),
            new Jogador("Samet Akaydin","Çaykur Rizespor","Defensor"),
            new Jogador("Zeki Celik","Roma","Defensor"),
            new Jogador("Hakan Çalhanoglu","Inter de Milão","Meio-campista"),
            new Jogador("Ismail Yuksek","Fenerbahçe","Meio-campista"),
            new Jogador("Kaan Ayhan","Galatasaray","Meio-campista"),
            new Jogador("Orkun Kökçü","Besiktaş","Meio-campista"),
            new Jogador("Salih Ozcan","Borussia Dortmund","Meio-campista"),
            new Jogador("Arda Güler","Real Madrid","Atacante"),
            new Jogador("Barış Yılmaz","Galatasaray","Atacante"),
            new Jogador("Can Uzun","Eintracht Frankfurt","Atacante"),
            new Jogador("Deniz Gül","Porto","Atacante"),
            new Jogador("Irfan Kahveci","Kasımpasa","Atacante"),
            new Jogador("Kenan Yildiz","Juventus","Atacante"),
            new Jogador("Kerem Akturkoglu","Fenerbahçe","Atacante"),
            new Jogador("Oguz Aydin","Fenerbahçe","Atacante"),
            new Jogador("Yunus Akgun","Galatasaray","Atacante")
        )),
        new Selecao("Alemanha", List.of(
            new Jogador("Oliver Baumann","Hoffenheim","Goleiro"),
            new Jogador("Manuel Neuer","Bayern de Munique","Goleiro"),
            new Jogador("Alexander Nubel","Stuttgart","Goleiro"),
            new Jogador("Waldemar Anton","Borussia Dortmund","Defensor"),
            new Jogador("Nathaniel Brown","Eintracht Frankfurt","Defensor"),
            new Jogador("Joshua Kimmich","Bayern de Munique","Defensor"),
            new Jogador("David Raum","RB Leipzig","Defensor"),
            new Jogador("Antonio Rudiger","Real Madrid","Defensor"),
            new Jogador("Nico Schlotterbeck","Borussia Dortmund","Defensor"),
            new Jogador("Jonathan Tah","Bayern de Munique","Defensor"),
            new Jogador("Malick Thiaw","Newcastle","Defensor"),
            new Jogador("Nadiem Amiri","Mainz","Meio-campista"),
            new Jogador("Leon Goretzka","Bayern de Munique","Meio-campista"),
            new Jogador("Pascal Gross","Brighton","Meio-campista"),
            new Jogador("Lennart Karl","Bayern de Munique","Meio-campista"),
            new Jogador("Jamie Leweling","Stuttgart","Meio-campista"),
            new Jogador("Jamal Musiala","Bayern de Munique","Meio-campista"),
            new Jogador("Felix Nmecha","Borussia Dortmund","Meio-campista"),
            new Jogador("Aleksandar Pavlovic","Bayern de Munique","Meio-campista"),
            new Jogador("Leroy Sané","Galatasaray","Meio-campista"),
            new Jogador("Angelo Stiller","Stuttgart","Meio-campista"),
            new Jogador("Florian Wirtz","Liverpool","Meio-campista"),
            new Jogador("Maximilian Beier","Borussia Dortmund","Atacante"),
            new Jogador("Kai Havertz","Arsenal","Atacante"),
            new Jogador("Deniz Undav","Stuttgart","Atacante"),
            new Jogador("Nick Woltemade","Newcastle","Atacante")
        )),
        new Selecao("Curaçao", List.of(
            new Jogador("Tyrick Bodak","Telstar","Goleiro"),
            new Jogador("Trevor Doornbusch","VVV-Venlo","Goleiro"),
            new Jogador("Eloy Room","Cercle Brugge","Goleiro"),
            new Jogador("Riechedly Bazoer","Konyaspor","Defensor"),
            new Jogador("Joshua Brenet","Kayserispor","Defensor"),
            new Jogador("Roshon Van Eijma","RKC Waalwijk","Defensor"),
            new Jogador("Sherel Floranus","PEC Zwolle","Defensor"),
            new Jogador("Deveron Fonville","NEC Nijmegen","Defensor"),
            new Jogador("Jurien Gaari","Abha Club","Defensor"),
            new Jogador("Armando Obispo","PSV","Defensor"),
            new Jogador("Shurandy Sambo","Sparta Rotterdam","Defensor"),
            new Jogador("Juninho Bacuna","Volendam","Meio-campista"),
            new Jogador("Leandro Bacuna","Iğdır FK","Meio-campista"),
            new Jogador("Livano Comenencia","Zürich","Meio-campista"),
            new Jogador("Kevin Felida","Den Bosch","Meio-campista"),
            new Jogador("Ar'jany Martha","Rotherham United","Meio-campista"),
            new Jogador("Tyrese Noslin","Telstar","Meio-campista"),
            new Jogador("Godfried Roemeratoe","RKC Waalwijk","Meio-campista"),
            new Jogador("Jeremy Antonisse","AE Kifisia","Atacante"),
            new Jogador("Tahith Chong","Sheffield United","Atacante"),
            new Jogador("Kenji Gorré","Maccabi Haifa","Atacante"),
            new Jogador("Sontje Hansen","Middlesbrough","Atacante"),
            new Jogador("Gervane Kastaneer","Terengganu","Atacante"),
            new Jogador("Brandley Kuwas","Volendam","Atacante"),
            new Jogador("Jurgen Locadia","Miami FC","Atacante"),
            new Jogador("Jearl Margaritha","Beveren","Atacante")
        )),
        new Selecao("Costa do Marfim", List.of(
            new Jogador("Yahia Fofana","Caykur Rizespor","Goleiro"),
            new Jogador("Mohamed Koné","Royal Charleroi","Goleiro"),
            new Jogador("Alban Lafont","Panathinaikos","Goleiro"),
            new Jogador("Emmanuel Agbadou","Besiktas","Defensor"),
            new Jogador("Clément Akpa","Auxerre","Defensor"),
            new Jogador("Ousmane Diomande","Sporting","Defensor"),
            new Jogador("Guéla Doué","Strasbourg","Defensor"),
            new Jogador("Ghislain Konan","Gil Vicente","Defensor"),
            new Jogador("Odilon Kossounou","Atalanta","Defensor"),
            new Jogador("Evan Ndicka","Roma","Defensor"),
            new Jogador("Wilfried Singo","Galatasaray","Defensor"),
            new Jogador("Seko Fofana","Porto","Meio-campista"),
            new Jogador("Parfait Guiagon","Royal Charleroi","Meio-campista"),
            new Jogador("Christ Inao Oulaï","Trabzonspor","Meio-campista"),
            new Jogador("Franck Kessié","Al Ahli","Meio-campista"),
            new Jogador("Ibrahim Sangaré","Nottingham Forest","Meio-campista"),
            new Jogador("Jean Michaël Seri","NK Maribor","Meio-campista"),
            new Jogador("Simon Adingra","Sunderland","Atacante"),
            new Jogador("Ange-Yoan Bonny","Inter de Milão","Atacante"),
            new Jogador("Amad Diallo","Manchester United","Atacante"),
            new Jogador("Oumar Diakité","Club Brugge","Atacante"),
            new Jogador("Yan Diomande","RB Leipzig","Atacante"),
            new Jogador("Evann Guessand","Crystal Palace","Atacante"),
            new Jogador("Nicolas Pépé","Villarreal","Atacante"),
            new Jogador("Bazoumana Touré","Hoffenheim","Atacante"),
            new Jogador("Elye Wahi","Nice","Atacante")
        )),
        new Selecao("Equador", List.of(
            new Jogador("Hernán Galíndez","Huracán","Goleiro"),
            new Jogador("Moisés Ramírez","AE Kifisias","Goleiro"),
            new Jogador("Gonzalo Valle","LDU","Goleiro"),
            new Jogador("Willian Pacho","Paris Saint-Germain","Defensor"),
            new Jogador("Piero Hincapié","Arsenal","Defensor"),
            new Jogador("Joel Ordóñez","Club Brugge","Defensor"),
            new Jogador("Jackson Porozo","Tijuana","Defensor"),
            new Jogador("Félix Torres","Internacional","Defensor"),
            new Jogador("Pervis Estupiñán","Milan","Defensor"),
            new Jogador("Yaimar Medina","Genk","Defensor"),
            new Jogador("Ángelo Preciado","Atlético-MG","Defensor"),
            new Jogador("Moisés Caicedo","Chelsea","Meio-campista"),
            new Jogador("Jordy Alcívar","Independiente del Valle","Meio-campista"),
            new Jogador("Pedro Vite","Vancouver Whitecaps","Meio-campista"),
            new Jogador("Denil Castillo","Midtjylland","Meio-campista"),
            new Jogador("Alan Franco","Atlético-MG","Meio-campista"),
            new Jogador("Kendry Páez","River Plate","Meio-campista"),
            new Jogador("Nilson Angulo","Sunderland","Meio-campista"),
            new Jogador("Alan Minda","Atlético-MG","Atacante"),
            new Jogador("Gonzalo Plata","Flamengo","Atacante"),
            new Jogador("John Yeboah","Venezia","Atacante"),
            new Jogador("Enner Valencia","Pachuca","Atacante"),
            new Jogador("Jordy Caicedo","Huracán","Atacante"),
            new Jogador("Jeremy Arévalo","Stuttgart","Atacante"),
            new Jogador("Anthony Valencia","Royal Antwerp","Atacante"),
            new Jogador("Kevin Rodríguez","Union Saint-Gilloise","Atacante")
        )),
        new Selecao("Holanda", List.of(
            new Jogador("Mark Flekken","Bayer Leverkusen","Goleiro"),
            new Jogador("Robin Roefs","Sunderland","Goleiro"),
            new Jogador("Bart Verbruggen","Brighton","Goleiro"),
            new Jogador("Nathan Aké","Manchester City","Defensor"),
            new Jogador("Virgil van Dijk","Liverpool","Defensor"),
            new Jogador("Denzel Dumfries","Inter de Milão","Defensor"),
            new Jogador("Jorrel Hato","Chelsea","Defensor"),
            new Jogador("Jan Paul van Hecke","Brighton","Defensor"),
            new Jogador("Jurriën Timber","Arsenal","Defensor"),
            new Jogador("Micky van de Ven","Tottenham","Defensor"),
            new Jogador("Ryan Gravenberch","Liverpool","Meio-campista"),
            new Jogador("Frenkie de Jong","Barcelona","Meio-campista"),
            new Jogador("Teun Koopmeiners","Juventus","Meio-campista"),
            new Jogador("Tijjani Reijnders","Manchester City","Meio-campista"),
            new Jogador("Marten de Roon","Atalanta","Meio-campista"),
            new Jogador("Guus Til","PSV","Meio-campista"),
            new Jogador("Quinten Timber","Olympique de Marselha","Meio-campista"),
            new Jogador("Mats Wieffer","Brighton","Meio-campista"),
            new Jogador("Memphis Depay","Corinthians","Atacante"),
            new Jogador("Brian Brobbey","Sunderland","Atacante"),
            new Jogador("Cody Gakpo","Liverpool","Atacante"),
            new Jogador("Justin Kluivert","Bournemouth","Atacante"),
            new Jogador("Noa Lang","Galatasaray","Atacante"),
            new Jogador("Donyell Malen","Roma","Atacante"),
            new Jogador("Crysencio Summerville","West Ham","Atacante"),
            new Jogador("Wout Weghorst","Ajax","Atacante")
        )),
        new Selecao("Japão", List.of(
            new Jogador("Zion Suzuki","Parma","Goleiro"),
            new Jogador("Keisuke Osako","Sanfrecce Hiroshima","Goleiro"),
            new Jogador("Tomoki Hayakawa","Kashima Antlers","Goleiro"),
            new Jogador("Hiroki Ito","Bayern de Munique","Defensor"),
            new Jogador("Junnosuke Suzuki","Copenhagen","Defensor"),
            new Jogador("Ayumu Seko","Le Havre","Defensor"),
            new Jogador("Shogo Taniguchi","Sint-Truidense","Defensor"),
            new Jogador("Tsuyoshi Watanabe","Feyenoord","Defensor"),
            new Jogador("Ko Itakura","Ajax","Defensor"),
            new Jogador("Takehiro Tomiyasu","Ajax","Defensor"),
            new Jogador("Yukinari Sugawara","Werder Bremen","Defensor"),
            new Jogador("Yuto Nagatomo","FC Tokyo","Defensor"),
            new Jogador("Daichi Kamada","Crystal Palace","Meio-campista"),
            new Jogador("Ao Tanaka","Leeds United","Meio-campista"),
            new Jogador("Kaishu Sano","Mainz","Meio-campista"),
            new Jogador("Wataru Endo","Liverpool","Meio-campista"),
            new Jogador("Keito Nakamura","Stade de Reims","Meio-campista"),
            new Jogador("Daizen Maeda","Celtic","Meio-campista"),
            new Jogador("Ritsu Doan","Eintracht Frankfurt","Meio-campista"),
            new Jogador("Yuito Suzuki","Freiburg","Meio-campista"),
            new Jogador("Junya Ito","Genk","Meio-campista"),
            new Jogador("Ayase Ueda","Feyenoord","Atacante"),
            new Jogador("Koki Ogawa","NEC Nijmegen","Atacante"),
            new Jogador("Kento Shiogai","Wolfsburg","Atacante"),
            new Jogador("Keisuke Goto","Sint-Truiden","Atacante"),
            new Jogador("Takefusa Kubo","Real Sociedad","Atacante")
        )),
        new Selecao("Suécia", List.of(
            new Jogador("Viktor Johansson","Stoke City","Goleiro"),
            new Jogador("Kristoffer Nordfeldt","AIK","Goleiro"),
            new Jogador("Jacob Widell Zetterström","Derby County","Goleiro"),
            new Jogador("Hjalmar Ekdal","Burnley","Defensor"),
            new Jogador("Gabriel Gudmundsson","Leeds United","Defensor"),
            new Jogador("Isak Hien","Atalanta","Defensor"),
            new Jogador("Herman Johansson","FC Dallas","Defensor"),
            new Jogador("Gustaf Lagerbielk","Braga","Defensor"),
            new Jogador("Victor Lindelöf","Aston Villa","Defensor"),
            new Jogador("Eric Smith","St. Pauli","Defensor"),
            new Jogador("Carl Starfelt","Celta de Vigo","Defensor"),
            new Jogador("Elliot Stroud","Mjällby AIF","Defensor"),
            new Jogador("Daniel Svensson","Borussia Dortmund","Defensor"),
            new Jogador("Yasin Ayari","Brighton","Meio-campista"),
            new Jogador("Lucas Bergvall","Tottenham","Meio-campista"),
            new Jogador("Jesper Karlström","Udinese","Meio-campista"),
            new Jogador("Ken Sema","Pafos","Meio-campista"),
            new Jogador("Mattias Svanberg","Wolfsburg","Meio-campista"),
            new Jogador("Besfort Zeneli","Union Saint-Gilloise","Meio-campista"),
            new Jogador("Taha Ali","Malmö","Atacante"),
            new Jogador("Alexander Bernhardsson","Holstein Kiel","Atacante"),
            new Jogador("Anthony Elanga","Newcastle","Atacante"),
            new Jogador("Viktor Gyökeres","Arsenal","Atacante"),
            new Jogador("Gustaf Nilsson","Club Brugge","Atacante"),
            new Jogador("Benjamin Nygren","Celtic","Atacante"),
            new Jogador("Alexander Isak","Liverpool","Atacante")
        )),
        new Selecao("Tunísia", List.of(
            new Jogador("Aymen Dahmen","Sfax","Goleiro"),
            new Jogador("Sabri Ben Hassen","ES Sahel","Goleiro"),
            new Jogador("Abdelmouhib Chamakh","Club Africain","Goleiro"),
            new Jogador("Yan Valéry","Young Boys","Defensor"),
            new Jogador("Moutaz Neffati","Norrköping","Defensor"),
            new Jogador("Dylan Bronn","Servette","Defensor"),
            new Jogador("Raed Chikhaoui","Monastir","Defensor"),
            new Jogador("Montassar Talbi","Lorient","Defensor"),
            new Jogador("Adem Arous","Kasimpasa","Defensor"),
            new Jogador("Omar Rekik","Maribor","Defensor"),
            new Jogador("Ali Abdi","Nice","Defensor"),
            new Jogador("Mohamed Ben Hmida","Esperánce","Defensor"),
            new Jogador("Ellyes Skhiri","Eintracht Frankfurt","Meio-campista"),
            new Jogador("Anis Ben Slimane","Norwich City","Meio-campista"),
            new Jogador("Rani Khedira","Union Berlin","Meio-campista"),
            new Jogador("Mortadha Ben Ouanes","Kasimpasa","Meio-campista"),
            new Jogador("Ken Sema","Pafos","Meio-campista"),
            new Jogador("Ismaël Gharbi","Augsburg","Meio-campista"),
            new Jogador("Mohamed Hadj-Mahmoud","Lugano","Meio-campista"),
            new Jogador("Hannibal Mejbri","Burnley","Meio-campista"),
            new Jogador("Elias Saäd","Hannover","Atacante"),
            new Jogador("Khalil Ayari","Paris Saint-Germain","Atacante"),
            new Jogador("Elias Achouri","Copenhagen","Atacante"),
            new Jogador("Sebastian Tounekti","Celtic","Atacante"),
            new Jogador("Hazem Mastouri","Dynamo Makhachkala","Atacante"),
            new Jogador("Firas Chawat","Club Africain","Atacante"),
            new Jogador("Rayan Elloumi","Vancouver Whitecaps","Atacante")
        )),
        new Selecao("Bélgica", List.of(
            new Jogador("Thibaut Courtois","Real Madrid","Goleiro"),
            new Jogador("Senne Lammens","Manchester United","Goleiro"),
            new Jogador("Mike Penders","Strasbourg","Goleiro"),
            new Jogador("Timothy Castagne","Fulham","Defensor"),
            new Jogador("Zeno Debast","Sporting","Defensor"),
            new Jogador("Koni De Winter","Milan","Defensor"),
            new Jogador("Brandon Mechele","Club Brugge","Defensor"),
            new Jogador("Arthur Theate","Eintracht Frankfurt","Defensor"),
            new Jogador("Maxim De Cuyper","Brighton","Defensor"),
            new Jogador("Thomas Meunier","Lille","Defensor"),
            new Jogador("Nathan Ngoy","Lille","Defensor"),
            new Jogador("Joaquin Seys","Club Brugge","Defensor"),
            new Jogador("Kevin De Bruyne","Napoli","Meio-campista"),
            new Jogador("Amadou Onana","Aston Villa","Meio-campista"),
            new Jogador("Nicolas Raskin","Rangers","Meio-campista"),
            new Jogador("Youri Tielemans","Aston Villa","Meio-campista"),
            new Jogador("Hans Vanaken","Club Brugge","Meio-campista"),
            new Jogador("Axel Witsel","Girona","Meio-campista"),
            new Jogador("Charles De Ketelaere","Atalanta","Atacante"),
            new Jogador("Mathias Fernandez-Pardo","Lille","Atacante"),
            new Jogador("Jeremy Doku","Manchester City","Atacante"),
            new Jogador("Romelu Lukaku","Napoli","Atacante"),
            new Jogador("Alexis Saelemaekers","Milan","Atacante"),
            new Jogador("Leandro Trossard","Arsenal","Atacante"),
            new Jogador("Dodi Lukebakio","Benfica","Atacante"),
            new Jogador("Diego Moreira","Strasbourg","Atacante")
        )),
        new Selecao("Egito", List.of(
            new Jogador("Mohamed El Shenawy","Al Ahly","Goleiro"),
            new Jogador("Mostafa Shobeir","Al Ahly","Goleiro"),
            new Jogador("El Mahdy Soliman","Zamalek","Goleiro"),
            new Jogador("Mohamed Alaa","El Gouna","Goleiro"),
            new Jogador("Mohamed Hany","Al Ahly","Defensor"),
            new Jogador("Tarek Alaa","Zed","Defensor"),
            new Jogador("Hamdi Fathi","Al Wakrah","Defensor"),
            new Jogador("Ramy Rabia","Al Ain","Defensor"),
            new Jogador("Yasser Ibrahim","Al Ahly","Defensor"),
            new Jogador("Hossam Abdelmaguid","Zamalek","Defensor"),
            new Jogador("Mohamed Abdelmonem","Nice","Defensor"),
            new Jogador("Ahmed Fatouh","Zamalek","Defensor"),
            new Jogador("Karim Hafez","Pyramids","Defensor"),
            new Jogador("Marwan Attia","Al Ahly","Meio-campista"),
            new Jogador("Mohannad Lasheen","Pyramids","Meio-campista"),
            new Jogador("Nabil Emad Dunga","Al Najma","Meio-campista"),
            new Jogador("Mahmoud Saber","Zed","Meio-campista"),
            new Jogador("Ahmed Sayed Zizo","Al Ahly","Meio-campista"),
            new Jogador("Mahmoud Trezeguet","Al Ahly","Meio-campista"),
            new Jogador("Emam Ashour","Al Ahly","Meio-campista"),
            new Jogador("Mostafa Ziko","Pyramids","Meio-campista"),
            new Jogador("Ibrahim Adel","Nordsjaelland","Meio-campista"),
            new Jogador("Haitham Hassan","Real Oviedo","Meio-campista"),
            new Jogador("Mohamed Salah","Liverpool","Atacante"),
            new Jogador("Omar Marmoush","Manchester City","Atacante"),
            new Jogador("Aktay Abdullah","Enppi","Atacante"),
            new Jogador("Hamza Abdel Karim","Al Ahly","Atacante")
        )),
        new Selecao("Irã", List.of(
            new Jogador("Alireza Beiranvand","Tractor","Goleiro"),
            new Jogador("Hossein Hosseini","Sepahan","Goleiro"),
            new Jogador("Payam Niazmand","Persepolis","Goleiro"),
            new Jogador("Shoja Khalilzadeh","Tractor","Defensor"),
            new Jogador("Hossein Kanaani","Persepolis","Defensor"),
            new Jogador("Ali Nemati","Foolad","Defensor"),
            new Jogador("Danial Eiri","Malavan Bandar Anzali","Defensor"),
            new Jogador("Ehsan Hajisafi","Sepahan","Defensor"),
            new Jogador("Milad Mohammadi","Persepolis","Defensor"),
            new Jogador("Saleh Hardani","Esteghlal","Defensor"),
            new Jogador("Ramin Rezaeian","Foolad","Defensor"),
            new Jogador("Saman Ghodos","Kalba FC","Meio-campista"),
            new Jogador("Saeid Ezatollahi","Shabab Al Ahli","Meio-campista"),
            new Jogador("Rouzbeh Cheshmi","Esteghlal","Meio-campista"),
            new Jogador("Amir Mohammad","Esteghlal","Meio-campista"),
            new Jogador("Amirmohammad Razzaghinia","Esteghlal","Meio-campista"),
            new Jogador("Mohammad Ghorbani","Al Wahda","Meio-campista"),
            new Jogador("Mehdi Ghayedi","Al Nasr SC","Meio-campista"),
            new Jogador("Arya Yousefi","Sepahan","Meio-campista"),
            new Jogador("Alireza Jahanbakhsh","Dender","Meio-campista"),
            new Jogador("Mehdi Torabi","Tractor","Meio-campista"),
            new Jogador("Mohammad Mohebi","Rostov","Meio-campista"),
            new Jogador("Mehdi Taremi","Olympiacos","Atacante"),
            new Jogador("Amirhossein Hosseinzadeh","Tractor","Atacante"),
            new Jogador("Dennis Dargahi","Standard Liège","Atacante"),
            new Jogador("Ali Alipour","Persepolis","Atacante"),
            new Jogador("Shahriar Moghanlou","Kalba FC","Atacante")
        )),
        new Selecao("Nova Zelândia", List.of(
            new Jogador("Max Crocombe","Millwall","Goleiro"),
            new Jogador("Alex Paulsen","Lechia Gdańsk","Goleiro"),
            new Jogador("Michael Woud","Auckland FC","Goleiro"),
            new Jogador("Tyler Bindon","Sheffield United","Defensor"),
            new Jogador("Michael Boxall","Minnesota United","Defensor"),
            new Jogador("Liberato Cacace","Wrexham","Defensor"),
            new Jogador("Francis de Vries","Auckland FC","Defensor"),
            new Jogador("Callan Elliot","Auckland FC","Defensor"),
            new Jogador("Tim Payne","Wellington Phoenix","Defensor"),
            new Jogador("Nando Pijnaker","Auckland FC","Defensor"),
            new Jogador("Tommy Smith","Auckland FC","Defensor"),
            new Jogador("Finn Surman","Portland Timbers","Defensor"),
            new Jogador("Lachlan Bayliss","Newcastle Jets","Meio-campista"),
            new Jogador("Joe Bell","Viking","Meio-campista"),
            new Jogador("Matt Garbett","Peterborough","Meio-campista"),
            new Jogador("Ben Old","Saint-Étienne","Meio-campista"),
            new Jogador("Alex Rufer","Wellington Phoenix","Meio-campista"),
            new Jogador("Sarpreet Singh","Wellington Phoenix","Meio-campista"),
            new Jogador("Marko Stamenic","Swansea City","Meio-campista"),
            new Jogador("Ryan Thomas","PEC Zwolle","Meio-campista"),
            new Jogador("Kosta Barbarouses","Western Sydney Wanderers","Atacante"),
            new Jogador("Elijah Just","Motherwell","Atacante"),
            new Jogador("Callum McCowatt","Silkeborg","Atacante"),
            new Jogador("Jesse Randall","Auckland FC","Atacante"),
            new Jogador("Ben Waine","Wellington Phoenix","Atacante"),
            new Jogador("Chris Wood","Nottingham Forest","Atacante")
        )),
        new Selecao("Espanha", List.of(
            new Jogador("Unai Simón","Athletic Bilbao","Goleiro"),
            new Jogador("David Raya","Arsenal","Goleiro"),
            new Jogador("Joan García","Barcelona","Goleiro"),
            new Jogador("Marc Cucurella","Chelsea","Defensor"),
            new Jogador("Alejandro Grimaldo","Bayer Leverkusen","Defensor"),
            new Jogador("Pau Cubarsí","Barcelona","Defensor"),
            new Jogador("Aymeric Laporte","Athletic Bilbao","Defensor"),
            new Jogador("Marc Pubill","Atlético de Madrid","Defensor"),
            new Jogador("Eric García","Barcelona","Defensor"),
            new Jogador("Marcos Llorente","Atlético de Madrid","Defensor"),
            new Jogador("Pedro Porro","Tottenham","Defensor"),
            new Jogador("Pedri","Barcelona","Meio-campista"),
            new Jogador("Fabián Ruiz","Paris Saint-Germain","Meio-campista"),
            new Jogador("Martín Zubimendi","Arsenal","Meio-campista"),
            new Jogador("Gavi","Barcelona","Meio-campista"),
            new Jogador("Rodri","Manchester City","Meio-campista"),
            new Jogador("Álex Baena","Atlético de Madrid","Meio-campista"),
            new Jogador("Mikel Merino","Arsenal","Meio-campista"),
            new Jogador("Mikel Oyarzabal","Real Sociedad","Atacante"),
            new Jogador("Dani Olmo","Barcelona","Atacante"),
            new Jogador("Nico Williams","Athletic Bilbao","Atacante"),
            new Jogador("Yeremy Pino","Crystal Palace","Atacante"),
            new Jogador("Ferran Torres","Barcelona","Atacante"),
            new Jogador("Borja Iglesias","Celta de Vigo","Atacante"),
            new Jogador("Víctor Muñoz","Osasuna","Atacante"),
            new Jogador("Lamine Yamal","Barcelona","Atacante")
        )),
        new Selecao("Cabo Verde", List.of(
            new Jogador("Josimar Dias, \"Vozinha\"","Chaves","Goleiro"),
            new Jogador("Márcio da Rosa","PFC Montana","Goleiro"),
            new Jogador("Carlos Santos","San Diego FC","Goleiro"),
            new Jogador("Steven Moreira","Columbus Crew","Defensor"),
            new Jogador("Wagner Pina","Trabzonspor","Defensor"),
            new Jogador("Sidny Cabral","Benfica","Defensor"),
            new Jogador("Logan Costa","Villarreal","Defensor"),
            new Jogador("Roberto Lopes, \"Pico\"","Shamrock Rovers","Defensor"),
            new Jogador("Kelvin Pires","SJK","Defensor"),
            new Jogador("Ianique Tavares, \"Stopira\"","Torreense","Defensor"),
            new Jogador("Edilson Borges, \"Diney\"","Al Bataeh","Defensor"),
            new Jogador("Jamiro Monteiro","Gaziantep","Meio-campista"),
            new Jogador("Deroy Duarte","Ludogorets","Meio-campista"),
            new Jogador("Kevin Pina","Krasnodar","Meio-campista"),
            new Jogador("Laros Duarte","Puskás Akadémia","Meio-campista"),
            new Jogador("Telmo Arcanjo","Vitória de Guimarães","Meio-campista"),
            new Jogador("Yannick Semedo","Farense","Meio-campista"),
            new Jogador("João Paulo Fernandes","FCSB","Meio-campista"),
            new Jogador("Garry Rodrigues","Apollon Limassol","Atacante"),
            new Jogador("Jovane Cabral","Estrela Amadora","Atacante"),
            new Jogador("Ryan Mendes","Iğdır FK","Atacante"),
            new Jogador("Nuno da Costa","İstanbul Başakşehir","Atacante"),
            new Jogador("Dailon Livramento","Casa Pia","Atacante"),
            new Jogador("Gilson Benchimol","FC Akron Togliatti","Atacante"),
            new Jogador("Willy Semedo","AC Omonia","Atacante"),
            new Jogador("Hélio Varela","Maccabi Tel Aviv","Atacante")
        )),
        new Selecao("Arábia Saudita", List.of(
            new Jogador("Ahmed Al Kassar","Al Qadsiah","Goleiro"),
            new Jogador("Mohammed Al Owais","Al Ula","Goleiro"),
            new Jogador("Nawaf Al Aqidi","Al Nassr","Goleiro"),
            new Jogador("Saud Abdulhamid","Lens","Defensor"),
            new Jogador("Mohammed Abu Al Shamat","Al Qadsiah","Defensor"),
            new Jogador("Khalid Al Ghannam","Al Ettifaq","Defensor"),
            new Jogador("Moteb Al Harbi","Al Hilal","Defensor"),
            new Jogador("Abdulelah Al Amri","Al Nassr","Defensor"),
            new Jogador("Nawaf Boushal","Al Nassr","Defensor"),
            new Jogador("Hassan Kadesh","Al Ittihad","Defensor"),
            new Jogador("Ali Lajami","Al Hilal","Defensor"),
            new Jogador("Ali Majrashi","Al Ahli","Defensor"),
            new Jogador("Hassan Tambakti","Al Ahli","Defensor"),
            new Jogador("Jehad Thikri","Al Qadsiah","Defensor"),
            new Jogador("Nasser Al Dawsari","Al Hilal","Meio-campista"),
            new Jogador("Alaa Al Hajji","Neom","Meio-campista"),
            new Jogador("Ziyad Al Johani","Al Ahli","Meio-campista"),
            new Jogador("Musab Al Juwayr","Al Qadsiah","Meio-campista"),
            new Jogador("Abdullah Al Khaibari","Al Nassr","Meio-campista"),
            new Jogador("Mohammed Kanno","Al Hilal","Meio-campista"),
            new Jogador("Sultan Mandash","Al Hilal","Meio-campista"),
            new Jogador("Ayman Yahya","Al Nassr","Meio-campista"),
            new Jogador("Feras Al Brikan","Al Ahli","Atacante"),
            new Jogador("Salem Al Dawsari","Al Hilal","Atacante"),
            new Jogador("Abdullah Al Hamdan","Al Nassr","Atacante"),
            new Jogador("Saleh Al Shehri","Al Ittihad","Atacante")
        )),
        new Selecao("Uruguai", List.of(
            new Jogador("Sergio Rochet","Internacional","Goleiro"),
            new Jogador("Fernando Muslera","Estudiantes","Goleiro"),
            new Jogador("Santiago Mele","Monterrey","Goleiro"),
            new Jogador("Guillermo Varela","Flamengo","Defensor"),
            new Jogador("Ronald Araújo","Barcelona","Defensor"),
            new Jogador("José María Giménez","Atlético de Madrid","Defensor"),
            new Jogador("Santiago Bueno","Wolverhampton","Defensor"),
            new Jogador("Sebastián Cáceres","América-MEX","Defensor"),
            new Jogador("Mathías Olivera","Napoli","Defensor"),
            new Jogador("Joaquín Piquerez","Palmeiras","Defensor"),
            new Jogador("Matías Viña","River Plate","Defensor"),
            new Jogador("Manuel Ugarte","Manchester United","Meio-campista"),
            new Jogador("Emiliano Martínez","Palmeiras","Meio-campista"),
            new Jogador("Rodrigo Bentancur","Tottenham","Meio-campista"),
            new Jogador("Federico Valverde","Real Madrid","Meio-campista"),
            new Jogador("Agustín Canobbio","Fluminense","Meio-campista"),
            new Jogador("Juan Manuel Sanabria","Real Salt Lake","Meio-campista"),
            new Jogador("Giorgian De Arrascaeta","Flamengo","Meio-campista"),
            new Jogador("Nicolás de la Cruz","Flamengo","Meio-campista"),
            new Jogador("Rodrigo Zalazar","Sporting","Meio-campista"),
            new Jogador("Facundo Pellistri","Panathinaikos","Meio-campista"),
            new Jogador("Maximiliano Araújo","Sporting","Meio-campista"),
            new Jogador("Brian Rodríguez","América-MEX","Meio-campista"),
            new Jogador("Rodrigo Aguirre","Tigres","Atacante"),
            new Jogador("Federico Viñas","Real Oviedo","Atacante"),
            new Jogador("Darwin Núñez","Al Hilal","Atacante")
        )),
        new Selecao("França", List.of(
            new Jogador("Mike Maignan","Milan","Goleiro"),
            new Jogador("Robin Risser","Lens","Goleiro"),
            new Jogador("Brice Samba","Stade Rennais","Goleiro"),
            new Jogador("Lucas Digne","Aston Villa","Defensor"),
            new Jogador("Malo Gusto","Chelsea","Defensor"),
            new Jogador("Lucas Hernández","Paris Saint-Germain","Defensor"),
            new Jogador("Theo Hernández","Al Hilal","Defensor"),
            new Jogador("Ibrahima Konaté","Liverpool","Defensor"),
            new Jogador("Jules Koundé","Barcelona","Defensor"),
            new Jogador("William Saliba","Arsenal","Defensor"),
            new Jogador("Dayot Upamecano","Bayern de Munique","Defensor"),
            new Jogador("Maxence Lacroix","Crystal Palace","Defensor"),
            new Jogador("N'Golo Kanté","Fenerbahçe","Meio-campista"),
            new Jogador("Manu Koné","Roma","Meio-campista"),
            new Jogador("Adrien Rabiot","Milan","Meio-campista"),
            new Jogador("Aurélian Tchouaméni","Real Madrid","Meio-campista"),
            new Jogador("Warren Zaïre-Emery","Paris Saint-Germain","Meio-campista"),
            new Jogador("Maghnès Akliouche","Monaco","Atacante"),
            new Jogador("Bradley Barcola","Paris Saint-Germain","Atacante"),
            new Jogador("Rayan Cherki","Manchester City","Atacante"),
            new Jogador("Ousmane Dembélé","Paris Saint-Germain","Atacante"),
            new Jogador("Désiré Doué","Paris Saint-Germain","Atacante"),
            new Jogador("Jean-Philippe Mateta","Crystal Palace","Atacante"),
            new Jogador("Kylian Mbappé","Real Madrid","Atacante"),
            new Jogador("Michael Olise","Bayern de Munique","Atacante"),
            new Jogador("Marcus Thuram","Inter de Milão","Atacante")
        )),
        new Selecao("Senegal", List.of(
            new Jogador("Édouard Mendy","Al Ahli","Goleiro"),
            new Jogador("Mory Diaw","Le Havre","Goleiro"),
            new Jogador("Yehvann Diouf","Nice","Goleiro"),
            new Jogador("Krépin Diatta","Monaco","Defensor"),
            new Jogador("Antoine Mendy","Nice","Defensor"),
            new Jogador("Kalidou Koulibaly","Al Hilal","Defensor"),
            new Jogador("El Hadji Malick Diouf","West Ham","Defensor"),
            new Jogador("Mamadou Sarr","Strasbourg","Defensor"),
            new Jogador("Moussa Niakhaté","Lyon","Defensor"),
            new Jogador("Moustapha Mbow","Paris FC","Defensor"),
            new Jogador("Abdoulaye Seck","Maccabi Haifa","Defensor"),
            new Jogador("Ismaïl Jakobs","Galatasaray","Defensor"),
            new Jogador("Ilay Camara","Anderlecht","Defensor"),
            new Jogador("Idrissa Gana Gueye","Everton","Meio-campista"),
            new Jogador("Pape Gueye","Villarreal","Meio-campista"),
            new Jogador("Lamine Camara","Monaco","Meio-campista"),
            new Jogador("Habib Diarra","Strasbourg","Meio-campista"),
            new Jogador("Pathé Ciss","Rayo Vallecano","Meio-campista"),
            new Jogador("Pape Matar Sarr","Tottenham","Meio-campista"),
            new Jogador("Bara Sapoko Ndiaye","Bayern de Munique","Meio-campista"),
            new Jogador("Sadio Mané","Al Nassr","Atacante"),
            new Jogador("Ismaïla Sarr","Crystal Palace","Atacante"),
            new Jogador("Iliman Ndiaye","Everton","Atacante"),
            new Jogador("Assane Diao","Real Betis","Atacante"),
            new Jogador("Ibrahim Mbaye","Paris Saint-Germain","Atacante"),
            new Jogador("Nicolas Jackson","Chelsea","Atacante"),
            new Jogador("Bamba Dieng","Lorient","Atacante"),
            new Jogador("Chérif Ndiaye","Estrela Vermelha","Atacante")
        )),
        new Selecao("Iraque", List.of(
            new Jogador("Jalal Hassan","Al Zawraa","Goleiro"),
            new Jogador("Ahmed Basil","Al Shorta","Goleiro"),
            new Jogador("Fahad Talib","Al Talaba","Goleiro"),
            new Jogador("Merchas Doski","Viktoria Plzen","Defensor"),
            new Jogador("Ahmed Yahya","Al Shorta","Defensor"),
            new Jogador("Manaf Younis","Al Shorta","Defensor"),
            new Jogador("Akam Hashim","Al Zawraa","Defensor"),
            new Jogador("Zaid Tahsin","Pakhtakor Tashkent","Defensor"),
            new Jogador("Rebin Sulaka","Port FC","Defensor"),
            new Jogador("Frans Dhia Putros","PERSIB","Defensor"),
            new Jogador("Hussein Ali","Pogon Szczecin","Defensor"),
            new Jogador("Mustafa Saadoon","Al Shorta","Defensor"),
            new Jogador("Aimar Sher","Sarpsborg","Meio-campista"),
            new Jogador("Zaid Ismail","Al Talaba","Meio-campista"),
            new Jogador("Amir Al Ammari","Cracovia","Meio-campista"),
            new Jogador("Kevin Yaqoub","Aarhus","Meio-campista"),
            new Jogador("Zidane Iqbal","Utrecht","Meio-campista"),
            new Jogador("Ahmed Qasem","Nashville","Meio-campista"),
            new Jogador("Ibrahim Bayesh","Al Dhafra","Meio-campista"),
            new Jogador("Ali Jassim","Al Najma","Meio-campista"),
            new Jogador("Youssef Amyn","AEK Larnaca","Meio-campista"),
            new Jogador("Marko Farji","Venezia","Meio-campista"),
            new Jogador("Ali Al Hamadi","Luton Town","Atacante"),
            new Jogador("Aymen Hussein","Al Karma","Atacante"),
            new Jogador("Mohanad Ali","Dibba SCC","Atacante"),
            new Jogador("Ali Yousif","Al Talaba","Atacante")
        )),
        new Selecao("Noruega", List.of(
            new Jogador("Orjan Nyland","Sevilla","Goleiro"),
            new Jogador("Egil Selvik","Watford","Goleiro"),
            new Jogador("Sander Tangvik","Hamburgo","Goleiro"),
            new Jogador("Kristoffer Ajer","Brentford","Defensor"),
            new Jogador("Torbjorn Heggem","Bologna","Defensor"),
            new Jogador("Leo Østigard","Genoa","Defensor"),
            new Jogador("Henrik Falchener","Viking FK","Defensor"),
            new Jogador("Julian Ryerson","Borussia Dortmund","Defensor"),
            new Jogador("David Moller Wolfe","Wolverhamtpon","Defensor"),
            new Jogador("Marcus Pedersen","Torino","Defensor"),
            new Jogador("Frederik Bjorkan","Bodø/Glimt","Defensor"),
            new Jogador("Martin Ødegaard","Arsenal","Meio-campista"),
            new Jogador("Sondre Langas","Derby County","Meio-campista"),
            new Jogador("Thelo Aasgaard","Rangers","Meio-campista"),
            new Jogador("Fredrik Aursnes","Benfica","Meio-campista"),
            new Jogador("Sander Berge","Fulham","Meio-campista"),
            new Jogador("Kristian Thorstvedt","Sassuolo","Meio-campista"),
            new Jogador("Patrick Berg","Bodø/Glimt","Meio-campista"),
            new Jogador("Morten Thorsby","Cremonese","Meio-campista"),
            new Jogador("Erling Haaland","Manchester City","Atacante"),
            new Jogador("Alexander Sørtloth","Atlético de Madrid","Atacante"),
            new Jogador("Jorgen Strand Larsen","Crystal Palace","Atacante"),
            new Jogador("Antonio Nusa","RB Leipzig","Atacante"),
            new Jogador("Oscar Bobb","Fulham","Atacante"),
            new Jogador("Andreas Schjeldrup","Benfica","Atacante"),
            new Jogador("Jens Petter Hauge","Bodø/Glimt","Atacante")
        )),
        new Selecao("Argentina", List.of(
            new Jogador("Emiliano Martínez","Aston Villa","Goleiro"),
            new Jogador("Gerónimo Rulli","Olympique de Marselha","Goleiro"),
            new Jogador("Juan Musso","Atlético de Madrid","Goleiro"),
            new Jogador("Nahuel Molina","Atlético de Madrid","Defensor"),
            new Jogador("Gonzalo Montiel","River Plate","Defensor"),
            new Jogador("Cristian Romero","Tottenham","Defensor"),
            new Jogador("Nicolás Otamendi","Benfica","Defensor"),
            new Jogador("Lisandro Martínez","Manchester United","Defensor"),
            new Jogador("Leonardo Balerdi","Olympique de Marselha","Defensor"),
            new Jogador("Nicolás Tagliafico","Lyon","Defensor"),
            new Jogador("Facundo Medina","Olympique de Marselha","Defensor"),
            new Jogador("Rodrigo De Paul","Inter Miami","Meio-campista"),
            new Jogador("Enzo Fernández","Chelsea","Meio-campista"),
            new Jogador("Leandro Paredes","Boca Juniors","Meio-campista"),
            new Jogador("Alexis Mac Allister","Liverpool","Meio-campista"),
            new Jogador("Valentín Barco","Strasbourg","Meio-campista"),
            new Jogador("Giovani Lo Celso","Real Betis","Meio-campista"),
            new Jogador("Exequiel Palacios","Bayer Leverkusen","Meio-campista"),
            new Jogador("Thiago Almada","Atlético de Madrid","Meio-campista"),
            new Jogador("Nico Paz","Como","Meio-campista"),
            new Jogador("Lionel Messi","Inter Miami","Atacante"),
            new Jogador("Nico González","Atlético de Madrid","Atacante"),
            new Jogador("Giuliano Simeone","Atlético de Madrid","Atacante"),
            new Jogador("Flaco López","Palmeiras","Atacante"),
            new Jogador("Julián Álvarez","Atlético de Madrid","Atacante"),
            new Jogador("Lautaro Martínez","Inter de Milão","Atacante")
        )),
        new Selecao("Argélia", List.of(
            new Jogador("Luca Zidane","Granada","Goleiro"),
            new Jogador("Oussama Benbot","USM Alger","Goleiro"),
            new Jogador("Melvin Mastil","Stade Nyonnais","Goleiro"),
            new Jogador("Abdelatif Ramdane","MC Alger","Goleiro"),
            new Jogador("Rafik Belghali","Hellas Verona","Defensor"),
            new Jogador("Samir Chergui","Paris FC","Defensor"),
            new Jogador("Rayan Ait-Nouri","Manchester City","Defensor"),
            new Jogador("Jaouen Hadjam","Young Boys","Defensor"),
            new Jogador("Aissa Mandi","Lille","Defensor"),
            new Jogador("Ramy Bensebaini","Borussia Dortmund","Defensor"),
            new Jogador("Zineddine Belaid","JS Kabylie","Defensor"),
            new Jogador("Achref Abada","USM Alger","Defensor"),
            new Jogador("Mohamed Amine Tougai","Espérance de Tunis","Defensor"),
            new Jogador("Nabil Bentaleb","Lille","Meio-campista"),
            new Jogador("Hicham Boudaqui","Nice","Meio-campista"),
            new Jogador("Houssem Aouar","Al Ittihad","Meio-campista"),
            new Jogador("Farès Chaibi","Eintracht Frankfurt","Meio-campista"),
            new Jogador("Ibrahim Maza","Bayer Leverkusen","Meio-campista"),
            new Jogador("Yacine Titraoui","Royal Charleroi","Meio-campista"),
            new Jogador("Ramiz Zerrouki","Twente","Meio-campista"),
            new Jogador("Mohamed Amine Amoura","Wolfsburg","Atacante"),
            new Jogador("Nadhir Benbouali","Gyor","Atacante"),
            new Jogador("Adil Boulbina","Al Duhail","Atacante"),
            new Jogador("Farès Ghedjemis","Frosinone","Atacante"),
            new Jogador("Amine Gouri","Olympique de Marselha","Atacante"),
            new Jogador("Anis Hadj Moussa","Feyenoord","Atacante"),
            new Jogador("Riyad Mahrez","Al Ahli","Atacante")
        )),
        new Selecao("Áustria", List.of(
            new Jogador("Alexander Schlager","Red Bull Salzburg","Goleiro"),
            new Jogador("Florian Wiegele","Viktoria Plzeň","Goleiro"),
            new Jogador("Patrick Pentz","Brøndby","Goleiro"),
            new Jogador("David Affengruber","Elche","Defensor"),
            new Jogador("Kevin Danso","Tottenham","Defensor"),
            new Jogador("Stefan Posch","Mainz","Defensor"),
            new Jogador("David Alaba","Real Madrid","Defensor"),
            new Jogador("Philipp Lienhart","Freiburg","Defensor"),
            new Jogador("Phillipp Mwene","Mainz","Defensor"),
            new Jogador("Marco Friedl","Werder Bremen","Defensor"),
            new Jogador("Alexander Prass","Hoffenheim","Defensor"),
            new Jogador("Michael Svoboda","Veneza","Defensor"),
            new Jogador("Xaver Schlager","RB Leipzig","Meio-campista"),
            new Jogador("Nicolas Seiwald","RB Leipzig","Meio-campista"),
            new Jogador("Marcel Sabitzer","Borussia Dortmund","Meio-campista"),
            new Jogador("Florian Grillitsch","Braga","Meio-campista"),
            new Jogador("Carney Chukwuemeka","Borussia Dortmund","Meio-campista"),
            new Jogador("Romano Schmid","Werder Bremen","Meio-campista"),
            new Jogador("Christoph Baumgartner","RB Leipzig","Meio-campista"),
            new Jogador("Konrad Laimer","Bayern de Munique","Meio-campista"),
            new Jogador("Patrick Wimmer","Wolfsburg","Meio-campista"),
            new Jogador("Paul Wanner","PSV","Meio-campista"),
            new Jogador("Alessandro Schöpf","Wolfsberger","Meio-campista"),
            new Jogador("Marko Arnautovic","Estrela Vermelha","Atacante"),
            new Jogador("Michael Gregoritsch","Augsburg","Atacante"),
            new Jogador("Sasa Kalajdzic","LASK","Atacante")
        )),
        new Selecao("Jordânia", List.of(
            new Jogador("Yazeed Abu Laila","Al Hussein","Goleiro"),
            new Jogador("Abdullah Al Fakhouri","Al Wehdat","Goleiro"),
            new Jogador("Nour Bani Attiah","Al Faisaly","Goleiro"),
            new Jogador("Abdallah Nasib","Al Zawraa","Defensor"),
            new Jogador("Saed Al Rosan","Al Hussein","Defensor"),
            new Jogador("Yazan Al Arab","Seoul","Defensor"),
            new Jogador("Saleem Obaid","Al Hussein","Defensor"),
            new Jogador("Mohammad Abualnadi","Selangor","Defensor"),
            new Jogador("Husam Abu Dahab","Al Salmiya","Defensor"),
            new Jogador("Ihsan Haddad","Al Hussein","Defensor"),
            new Jogador("Anas Badawi","Al Faisaly","Defensor"),
            new Jogador("Mohannad Abu Taha","Al Quwa Al Jawiya","Defensor"),
            new Jogador("Mohammad Abu Hashish","Al Karma","Defensor"),
            new Jogador("Nour Al Rawabdeh","Selangor","Meio-campista"),
            new Jogador("Nizar Al Rashdan","Qatar SC","Meio-campista"),
            new Jogador("Ibrahim Sadeh","Al Karma","Meio-campista"),
            new Jogador("Rajaei Ayed","Al Hussein","Meio-campista"),
            new Jogador("Amer Jamous","Al Zawraa","Meio-campista"),
            new Jogador("Mohammad Al Dawoud","Al Wehda","Meio-campista"),
            new Jogador("Mahmoud Al Mardi","Al Hussein","Atacante"),
            new Jogador("Musa Al Taamari","Rennes","Atacante"),
            new Jogador("Mohammad Abu Zrayq","Raja Casablanca","Atacante"),
            new Jogador("Ali Al Azaizeh","Al Shabab","Atacante"),
            new Jogador("Odeh Fakhouri","Pyramids","Atacante"),
            new Jogador("Ibrahim Sabra","Lokomotiva Zagreb","Atacante"),
            new Jogador("Ali Olwan","Al Sailiya","Atacante")
        )),
        new Selecao("Portugal", List.of(
            new Jogador("Diogo Costa","Porto","Goleiro"),
            new Jogador("José Sá","Wolverhampton","Goleiro"),
            new Jogador("Rui Silva","Sporting","Goleiro"),
            new Jogador("Ricardo Velho","Gençlerbirliği","Goleiro"),
            new Jogador("Diogo Dalot","Manchester United","Defensor"),
            new Jogador("Matheus Nunes","Manchester City","Defensor"),
            new Jogador("Nelson Semedo","Fenerbahçe","Defensor"),
            new Jogador("João Cancelo","Barcelona","Defensor"),
            new Jogador("Nuno Mendes","Paris Saint-Germain","Defensor"),
            new Jogador("Gonçalo Inácio","Sporting","Defensor"),
            new Jogador("Renato Veiga","Villarreal","Defensor"),
            new Jogador("Rúben Dias","Manchester City","Defensor"),
            new Jogador("Tomás Araújo","Benfica","Defensor"),
            new Jogador("Rúben Neves","Al Hilal","Meio-campista"),
            new Jogador("Samuel Costa","Mallorca","Meio-campista"),
            new Jogador("João Neves","Paris Saint-Germain","Meio-campista"),
            new Jogador("Vitinha","Paris Saint-Germain","Meio-campista"),
            new Jogador("Bruno Fernandes","Manchester United","Meio-campista"),
            new Jogador("Bernardo Silva","Manchester City","Meio-campista"),
            new Jogador("João Félix","Al Nassr","Atacante"),
            new Jogador("Francisco Trincão","Sporting","Atacante"),
            new Jogador("Francisco Conceição","Juventus","Atacante"),
            new Jogador("Pedro Neto","Chelsea","Atacante"),
            new Jogador("Rafael Leão","Milan","Atacante"),
            new Jogador("Gonçalo Guedes","Real Sociedad","Atacante"),
            new Jogador("Gonçalo Ramos","Paris Saint-Germain","Atacante"),
            new Jogador("Cristiano Ronaldo","Al Nassr","Atacante")
        )),
        new Selecao("RD Congo", List.of(
            new Jogador("Timothy Fayulu","FC Noah","Goleiro"),
            new Jogador("Lionel Mpasi","Rodez","Goleiro"),
            new Jogador("Matthieu Epolo","Standard Liège","Goleiro"),
            new Jogador("Aaron Wan-Bissaka","West Ham","Defensor"),
            new Jogador("Gédéon Kalulu","Aris Limassol","Defensor"),
            new Jogador("Joris Kayembe","Genk","Defensor"),
            new Jogador("Arthur Masuaku","Lens","Defensor"),
            new Jogador("Steve Kapuadi","Widzew Łódź","Defensor"),
            new Jogador("Aaron Tshibola","Kilmarnock","Defensor"),
            new Jogador("Axel Tuanzebe","Burnley","Defensor"),
            new Jogador("Chancel Mbemba","Lille","Defensor"),
            new Jogador("Dylan Batubinsika","AE Larissa","Defensor"),
            new Jogador("Noah Sadiki","Sunderland","Meio-campista"),
            new Jogador("Samuel Moutoussamy","Atromitos","Meio-campista"),
            new Jogador("Edo Kayembe","Watford","Meio-campista"),
            new Jogador("Ngal'ayel Mukau","Lille","Meio-campista"),
            new Jogador("Charles Pickel","Espanyol","Meio-campista"),
            new Jogador("Nathanael Mbuku","Augsburg","Meio-campista"),
            new Jogador("Brian Cipenga","CD Castellón","Meio-campista"),
            new Jogador("Theo Bongonda","Spartak Moscou","Meio-campista"),
            new Jogador("Gael Kakuta","Sakaryaspor","Meio-campista"),
            new Jogador("Meschack Elia","Young Boys","Atacante"),
            new Jogador("Fiston Mayele","Pyramids","Atacante"),
            new Jogador("Cédric Bakambu","Real Betis","Atacante"),
            new Jogador("Simon Banza","Al Jazira","Atacante"),
            new Jogador("Yoane Wissa","Newcastle","Atacante")
        )),
        new Selecao("Uzbequistão", List.of(
            new Jogador("Utkir Yusupov","Navbahor","Goleiro"),
            new Jogador("Abduvohid Nematov","Nasaf","Goleiro"),
            new Jogador("Botirali Ergashev","Neftchi Farg'ona","Goleiro"),
            new Jogador("Abdukodir Khusanov","Manchester City","Defensor"),
            new Jogador("Khojiakbar Alijonov","Pakhtakor","Defensor"),
            new Jogador("Farrukh Sayfiev","Neftchi Farg'ona","Defensor"),
            new Jogador("Rustam Ashurmatov","Esteghlal","Defensor"),
            new Jogador("Umar Eshmurodov","Nasaf","Defensor"),
            new Jogador("Sherzod Nasrullaev","Nasaf","Defensor"),
            new Jogador("Abdulla Abdullaev","Dibba","Defensor"),
            new Jogador("Avazbek Ulmasaliev","AGMK","Defensor"),
            new Jogador("Jakhongir Urozov","Dinamo Samarcanda","Defensor"),
            new Jogador("Bekhruz Karimov","Surkhon","Defensor"),
            new Jogador("Akmal Mozgovoy","Pakhtakor","Meio-campista"),
            new Jogador("Otabek Shukurov","Baniyas","Meio-campista"),
            new Jogador("Jamshid Iskanderov","Neftchi Farg'ona","Meio-campista"),
            new Jogador("Odiljon Hamrobekov","Tractor","Meio-campista"),
            new Jogador("Jaloliddin Masharipov","Esteghlal","Meio-campista"),
            new Jogador("Oston Urunov","Persepolis","Meio-campista"),
            new Jogador("Dostonbek Khamdamov","Pakhtakor","Meio-campista"),
            new Jogador("Aziz Ganiev","Al Bataeh","Meio-campista"),
            new Jogador("Abbosbek Fayzullaev","İstanbul Başakşehir","Meio-campista"),
            new Jogador("Sherzod Esanov","Bukhara","Meio-campista"),
            new Jogador("Eldor Shomurodov","İstanbul Başakşehir","Atacante"),
            new Jogador("Igor Sergeev","Pakhtakor","Atacante"),
            new Jogador("Azizbek Amonov","Buxoro","Atacante")
        )),
        new Selecao("Colômbia", List.of(
            new Jogador("Camilo Vargas","Atlas","Goleiro"),
            new Jogador("Álvaro Montero","Vélez Sarsfield","Goleiro"),
            new Jogador("David Ospina","Atlético Nacional","Goleiro"),
            new Jogador("Davinson Sánchez","Galatasaray","Defensor"),
            new Jogador("Jhon Lucumí","Bologna","Defensor"),
            new Jogador("Yerry Mina","Cagliari","Defensor"),
            new Jogador("Willer Ditta","Cruz Azul","Defensor"),
            new Jogador("Daniel Muñoz","Crystal Palace","Defensor"),
            new Jogador("Santiago Arias","Independiente","Defensor"),
            new Jogador("Johan Mojica","Mallorca","Defensor"),
            new Jogador("Deiver Machado","Nantes","Defensor"),
            new Jogador("Richard Ríos","Benfica","Meio-campista"),
            new Jogador("Jefferson Lerma","Crystal Palace","Meio-campista"),
            new Jogador("Kevin Castaño","River Plate","Meio-campista"),
            new Jogador("Juan Portilla","Athletico-PR","Meio-campista"),
            new Jogador("Gustavo Puerta","Racing Santander","Meio-campista"),
            new Jogador("Jhon Árias","Palmeiras","Meio-campista"),
            new Jogador("Jorge Carrascal","Flamengo","Meio-campista"),
            new Jogador("Juan Fernando Quintero","River Plate","Meio-campista"),
            new Jogador("James Rodríguez","Minnesota United","Meio-campista"),
            new Jogador("Jáminton Campaz","Rosario Central","Meio-campista"),
            new Jogador("Cucho Hernández","Real Betis","Atacante"),
            new Jogador("Luis Díaz","Bayern de Munique","Atacante"),
            new Jogador("Luis Suárez","Sporting","Atacante"),
            new Jogador("Andrés Gómez","Vasco","Atacante"),
            new Jogador("Jhon Córdoba","Krasnodar","Atacante")
        )),
        new Selecao("Inglaterra", List.of(
            new Jogador("Jordan Pickford","Everton","Goleiro"),
            new Jogador("Dean Henderson","Crystal Palace","Goleiro"),
            new Jogador("James Trafford","Manchester City","Goleiro"),
            new Jogador("Reece James","Chelsea","Defensor"),
            new Jogador("Tino Livramento","Newcastle","Defensor"),
            new Jogador("Marc Guehi","Manchester City","Defensor"),
            new Jogador("Ezri Konsa","Aston Villa","Defensor"),
            new Jogador("John Stones","Manchester City","Defensor"),
            new Jogador("Jarell Quansah","Bayer Leverkusen","Defensor"),
            new Jogador("Nico O'Reilly","Manchester City","Defensor"),
            new Jogador("Dan Burn","Newcastle","Defensor"),
            new Jogador("Djed Spence","Tottenham","Defensor"),
            new Jogador("Declan Rice","Arsenal","Meio-campista"),
            new Jogador("Elliot Anderson","Nottingham Forest","Meio-campista"),
            new Jogador("Jude Bellingham","Real Madrid","Meio-campista"),
            new Jogador("Jordan Henderson","Brentford","Meio-campista"),
            new Jogador("Morgan Rogers","Aston Villa","Meio-campista"),
            new Jogador("Kobbie Mainoo","Manchester United","Meio-campista"),
            new Jogador("Eberechi Eze","Arsenal","Meio-campista"),
            new Jogador("Harry Kane","Bayern de Munique","Atacante"),
            new Jogador("Ivan Toney","Al Ahli","Atacante"),
            new Jogador("Ollie Watkins","Aston Villa","Atacante"),
            new Jogador("Bukayo Saka","Arsenal","Atacante"),
            new Jogador("Noni Madueke","Arsenal","Atacante"),
            new Jogador("Marcus Rashford","Barcelona","Atacante"),
            new Jogador("Anthony Gordon","Newcastle","Atacante")
        )),
        new Selecao("Croácia", List.of(
            new Jogador("Dominik Livakovic","Dínamo Zagreb","Goleiro"),
            new Jogador("Dominik Kotarski","Copenhagen","Goleiro"),
            new Jogador("Ivor Pandur","Hull City","Goleiro"),
            new Jogador("Josko Gvardiol","Manchester City","Defensor"),
            new Jogador("Duje Caleta-Car","Real Sociedad","Defensor"),
            new Jogador("Josip Sutalo","Ajax","Defensor"),
            new Jogador("Josip Stanisic","Bayern de Munique","Defensor"),
            new Jogador("Marin Pongracic","Fiorentina","Defensor"),
            new Jogador("Martin Erlic","Midtjylland","Defensor"),
            new Jogador("Luka Vuskovic","Hamburgo","Defensor"),
            new Jogador("Luka Modric","Milan","Meio-campista"),
            new Jogador("Mateo Kovacic","Manchester City","Meio-campista"),
            new Jogador("Mario Pasalic","Atalanta","Meio-campista"),
            new Jogador("Nikola Vlasic","Torino","Meio-campista"),
            new Jogador("Luka Sucic","Real Sociedad","Meio-campista"),
            new Jogador("Martin Baturina","Como","Meio-campista"),
            new Jogador("Kristijan Jakic","Augsburg","Meio-campista"),
            new Jogador("Petar Sucic","Inter de Milão","Meio-campista"),
            new Jogador("Nikola Moro","Bologna","Meio-campista"),
            new Jogador("Toni Fruk","HNK Rijeka","Meio-campista"),
            new Jogador("Ivan Perisic","PSV","Atacante"),
            new Jogador("Andrej Kramaric","Hoffenheim","Atacante"),
            new Jogador("Ante Budimir","Osasuna","Atacante"),
            new Jogador("Marco Pasalic","Orlando City","Atacante"),
            new Jogador("Petar Musa","Dallas","Atacante"),
            new Jogador("Igor Matanovic","Freiburg","Atacante")
        )),
        new Selecao("Gana", List.of(
            new Jogador("Benjamin Asare","Hearts of Oak","Goleiro"),
            new Jogador("Lawrence Ati-Zigi","St. Gallen","Goleiro"),
            new Jogador("Joseph Anang","St. Patrick","Goleiro"),
            new Jogador("Baba Abdul Rahman","Paok","Defensor"),
            new Jogador("Gideoh Mensah","Auxerre","Defensor"),
            new Jogador("Marvin Senaya","Auxerre","Defensor"),
            new Jogador("Alidu Seidu","Rennes","Defensor"),
            new Jogador("Abdul Mumin","Rayo Vallecano","Defensor"),
            new Jogador("Jerome Opoku","İstanbul Başakşehir","Defensor"),
            new Jogador("Jonas Adjetey","Wolfsburg","Defensor"),
            new Jogador("Kojo Oppong Peprah","Nice","Defensor"),
            new Jogador("Derrick Luckassen","Pafos","Defensor"),
            new Jogador("Elisha Owusu","Auxerre","Meio-campista"),
            new Jogador("Thomas Partey","Villarreal","Meio-campista"),
            new Jogador("Kwasi Sibo","Real Oviedo","Meio-campista"),
            new Jogador("Augustine Boakye","Saint-Étienne","Meio-campista"),
            new Jogador("Caleb Yirenkyi","Nordsjaelland","Meio-campista"),
            new Jogador("Abdul Fatawu Issahaku","Leicester City","Meio-campista"),
            new Jogador("Christopher Bonsu Baah","Al Qadsiah","Atacante"),
            new Jogador("Ernest Nuamah","Lyon","Atacante"),
            new Jogador("Antoine Semenyo","Manchester City","Atacante"),
            new Jogador("Brandon Thomas-Asante","Coventry City","Atacante"),
            new Jogador("Kamal Deen Sulemana","Atalanta","Atacante"),
            new Jogador("Prince Kwabena Adu","Viktoria Plzeň","Atacante"),
            new Jogador("Iñaki Williams","Athletic Bilbao","Atacante"),
            new Jogador("Jordan Ayew","Leicester City","Atacante")
        )),
        new Selecao("Panamá", List.of(
            new Jogador("Orlando Mosquera","Al Fayha","Goleiro"),
            new Jogador("Luis Mejía","Nacional-URU","Goleiro"),
            new Jogador("César Samudio","Marathón","Goleiro"),
            new Jogador("César Blackman","Slovan Bratislava","Defensor"),
            new Jogador("Jorge Gutiérrez","Deportivo La Guaira","Defensor"),
            new Jogador("Amir Murillo","Besiktas","Defensor"),
            new Jogador("Fidel Escobar","Deportivo Saprissa","Defensor"),
            new Jogador("Andrés Andrade","LASK","Defensor"),
            new Jogador("Edgardo Fariña","Pari Nizhniy Novgorod","Defensor"),
            new Jogador("José Córdoba","Norwich City","Defensor"),
            new Jogador("Eric Davis","Plaza Amador","Defensor"),
            new Jogador("Jiovany Ramos","Academia Puerto Cabello","Defensor"),
            new Jogador("Roderick Miller","Turan-Tovuz","Defensor"),
            new Jogador("Aníbal Godoy","San Diego","Meio-campista"),
            new Jogador("Adalberto Carrasquilla","Pumas","Meio-campista"),
            new Jogador("Carlos Harvey","Minnesota United","Meio-campista"),
            new Jogador("Cristian Martínez","Ironi Kiryat Shmona","Meio-campista"),
            new Jogador("José Luis Rodríguez","Juárez","Meio-campista"),
            new Jogador("César Yanis","Cobresal","Meio-campista"),
            new Jogador("Yoel Bárcenas","Mazatlán","Meio-campista"),
            new Jogador("Alberto Quintero","Plaza Amador","Meio-campista"),
            new Jogador("Azarías Londoño","Universidad Católica-EQU","Meio-campista"),
            new Jogador("Ismael Díaz","León","Atacante"),
            new Jogador("Cecilio Waterman","Universidad de Concepción","Atacante"),
            new Jogador("José Fajardo","Universidad Católica-EQU","Atacante"),
            new Jogador("Tomás Rodríguez","Deportivo Saprissa","Atacante")
        ))
    );
}